# Docker

# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  GITHUB_CREDS_USR: '$(GITHUB_CREDS_USR)'
  EDGE_VERSION: '$(EDGE_VERSION)'
  TLSVERIFY: '$(TLSVERIFY)'
  IMAGE: '$(IMAGE)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: OpenShift
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          buildah bud \
                --tls-verify=$TLSVERIFY \
                --build-arg EDGE_VERSION=$EDGE_VERSION \
                --build-arg GITHUB_CREDS_USR=$GITHUB_CREDS_USR \
                --build-arg GITHUB_CREDS_PSW=$GITHUB_CREDS_PSW \
                -t $IMAGE \
                .
        env:
          GITHUB_CREDS_PSW: $(GITHUB_CREDS_PSW)